# Generated by Django 6.0.7 on 2026-07-12 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcebooking',
            name='google_sync_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resourcebooking',
            name='outlook_sync_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
